[package]
name = "fireball"
version = "0.1.0"
authors = ["Max Verevkin <me@maxverevkin.tk>"]
description = "This program aims to reconstruct the trajectory of a fireball given only data collected from witnesses"
edition = "2018"

[dependencies]
rand = "0.8.1"
crossbeam-utils = "0.8.3"

[dependencies.clap]
version = "2.33.3"
default-features = false

[profile.release]
panic = 'abort'
lto = 'fat'
debug = true
