[package]
name = "common"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_distr = "0.4"
rand = { version = "0.8", features = ["nightly", "small_rng"] }
plotters = "0.3"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.7.2"
